blank_issues_enabled: true
contact_links:
  - name: New issue
    url: >-
      https://github.com/StakerSea/ResumeAigent/blob/v3/.github/CONTRIBUTING.md
    about: "Before opening a new issue, please make sure to read CONTRIBUTING.md"
